output "name" {
  value = {
    "resource group" = "${var.projName}${local.loc_abbr}rg${var.iterator}"
    "subscription" = "${var.projName}${local.loc_abbr}sub${var.iterator}"
    "management group" = "${var.projName}${local.loc_abbr}mg${var.iterator}"
    "virtual network" = "${var.projName}${local.loc_abbr}vnet${var.iterator}"
    "subnet" = "${var.projName}${local.loc_abbr}subnet${var.iterator}"
    "network interface" = "${var.projName}${local.loc_abbr}nic${var.iterator}"
    "network security group" = "${var.projName}${local.loc_abbr}nsg${var.iterator}"
    "public ip" = "${var.projName}${local.loc_abbr}pip${var.iterator}"
    "private endpoint" = "${var.projName}${local.loc_abbr}pep${var.iterator}"
    "dns zone" = "${var.projName}${local.loc_abbr}dnsz${var.iterator}"
    "vwan" = "${var.projName}${local.loc_abbr}vwan${var.iterator}"
    "vhub" = "${var.projName}${local.loc_abbr}vhub${var.iterator}"
    "firewall" = "${var.projName}${local.loc_abbr}azfw${var.iterator}"
    "route table" = "${var.projName}${local.loc_abbr}rt${var.iterator}"
    "virtual machine" = "${var.projName}${local.loc_abbr}vm${var.iterator}"
    "disk" = "${var.projName}${local.loc_abbr}disk${var.iterator}"
    "image" = "${var.projName}${local.loc_abbr}img${var.iterator}"
    "snapshot" = "${var.projName}${local.loc_abbr}snp${var.iterator}"
    "storage account" = "${var.projName}${local.loc_abbr}st${var.iterator}"
    "blob container" = "${var.projName}${local.loc_abbr}blob${var.iterator}"
    "fileshare" = "${var.projName}${local.loc_abbr}file${var.iterator}"
    "queue" = "${var.projName}${local.loc_abbr}queue${var.iterator}"
    "table" = "${var.projName}${local.loc_abbr}table${var.iterator}"
    "data lake" = "${var.projName}${local.loc_abbr}dls${var.iterator}"
    "sql server" = "${var.projName}${local.loc_abbr}sql${var.iterator}"
    "sql database" = "${var.projName}${local.loc_abbr}sqldb${var.iterator}"
    "postgres" = "${var.projName}${local.loc_abbr}psql${var.iterator}"
    "mysql" = "${var.projName}${local.loc_abbr}mysql${var.iterator}"
    "mariadb" = "${var.projName}${local.loc_abbr}maria${var.iterator}"
    "cosmos" = "${var.projName}${local.loc_abbr}cos${var.iterator}"
  }
  description = "Map of resource type to standardized name"
}